language: nix
sudo: required
before_script:
- sudo mount -o remount,exec,size=4G,mode=755 /run/user || true

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

script:
  - rm -rf $HOME/.stack/setup-exe-cache
  - nix-shell -p stack --run "stack --no-terminal --nix test"
