name:                mixpanel-client
version:             0.1.0.0
github:              "domenkozar/mixpanel-client"
license:             Apache-2.0
author:              "Domen Kožar"
maintainer:          "domen@enlambda.com"
copyright:           "2018 Domen Kožar"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis: Mixpanel client

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- base64-bytestring
- transformers
- http-client
- http-client-tls
- servant >= 0.14.1
- servant-client
- string-conv
- text
- time

default-extensions:
- OverloadedStrings
- LambdaCase
- DeriveGeneric
- DeriveFunctor
- DeriveAnyClass
- RecordWildCards

ghc-options:
  -Wall
  -fwarn-tabs
  -fwarn-unused-imports
  -fwarn-missing-signatures
  -fwarn-name-shadowing
  -fwarn-incomplete-patterns

library:
  source-dirs: src

tests:
  mixpanel-test:
    main:                Main.hs
    source-dirs:         test
    dependencies:
    - mixpanel-client
    - hspec
    verbatim:
      build-tool-depends: hspec-discover:hspec-discover

  readme:
    main: README.lhs
    dependencies:
    - base
    - mixpanel-client
    - markdown-unlit
    ghc-options:
    - -pgmL markdown-unlit
